ls:
  .js: camelCase | point.case
  .ts: camelCase | point.case

ignore:
  - dist
  - packages/**/dist
  - coverage
  - .git
  - .github
  - .vscode
  - .idea
  - .yarn
  - packages/web-news/.next
  - packages/web-news/next-env.d.ts
