ls:
  .js: camelCase | point.case
  .ts: camelCase | point.case

ignore:
  - dist
  - packages/news-admin/dist
  - packages/news-admin/node_modules
  - packages/*/node_modules
  - packages/news/.next
  - packages/news/next-env.d.ts
  - packages/news/src/typings
  - node_modules
  - coverage
  - .git
  - .github
  - .vscode
  - .idea
  - .yarn
