name: Compressed Size

on:
  pull_request:
    branches:
      - '**'

jobs:
  bundlesize:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v1
        with:
          repo-token: '${{ secrets.GH_TOKEN }}'
          pattern: './dist/**/*.{js,mjs}'
